// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBuYESaNf2FGgSZk18vfZj3BNGkLNCogY',
    appId: '1:359871841829:web:508ed61abfa04de257a1cc',
    messagingSenderId: '359871841829',
    projectId: 'work-space-new',
    authDomain: 'work-space-new.firebaseapp.com',
    storageBucket: 'work-space-new.appspot.com',
    measurementId: 'G-8DZ5CMC4GE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeY4XZ_y7FItR1SjZ0GlWWzPProwwssxE',
    appId: '1:359871841829:android:a77441faec69fe9357a1cc',
    messagingSenderId: '359871841829',
    projectId: 'work-space-new',
    storageBucket: 'work-space-new.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6JkscpqlaUT7NoSM5tvarEF1X6xe_ydg',
    appId: '1:359871841829:ios:834aa933f81929e057a1cc',
    messagingSenderId: '359871841829',
    projectId: 'work-space-new',
    storageBucket: 'work-space-new.appspot.com',
    iosBundleId: 'com.example.laundryAppProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6JkscpqlaUT7NoSM5tvarEF1X6xe_ydg',
    appId: '1:359871841829:ios:2d84196f31fc567d57a1cc',
    messagingSenderId: '359871841829',
    projectId: 'work-space-new',
    storageBucket: 'work-space-new.appspot.com',
    iosBundleId: 'com.example.laundryAppProject.RunnerTests',
  );
}
